# Generated by Django 5.0.6 on 2024-06-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='contect',
            new_name='content',
        ),
    ]
