# Generated by Django 5.0.6 on 2024-06-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_author_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
