# Generated by Django 5.2.2 on 2025-06-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_user_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
